<body id="body">
<link href="css/bootstrap.css" rel="stylesheet">

<section class="vh-100" >
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10" style="margin-top: -20px">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-3 col-lg-4 d-none d-md-block">
                            <!--KRM Logo-->
                            <img src="../images/dot_krm.png" width="325px" height="325px" alt="" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin-top: 21.8%; width: %; height: %; float: right; margin-left: 20%">
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <!--Login Form-->
                                <form method="post" action="../index.php">


                                    <div class="flex-d align-items-center mb-3 pb-1">
                                        <label class="h1 fw-bold mb-0">Admin Login</label>
                                    </div>

                                    <h5 class="fw-normal mb-3 pb-4" style="letter-spacing: 1px;">Enter username and password</h5>

                                    <!--Username Input-->
                                    <div class="form-outline mb-4">
                                        <input type="text" id="form2Example17" name="userName" class="form-control form-control-lg" placeholder="Username" value="<?php if(isset($_POST['userName'])){echo $_POST['userName'];}?>" required>

                                    </div>

                                    <!--Password Input-->
                                    <div class="form-outline mb-4">
                                        <input type="password" id="form2Example27" name="password" class="form-control form-control-lg" placeholder="Password" value="<?php if(isset($_POST['password'])){echo $_POST['password'];}?>" required>

                                    </div>

                                    <!--Submit Login Details Button-->
                                    <div class="pt-1 mb-4" >
                                        <input class="btn btn-light btn-lg btn-outline-secondary" name="loginSubmitBtn" type="submit" value="Login">
                                    </div>
                                    <!--Error message for incorrect credentials-->
                                    <?php
                                    if(isset($AdminDataset->_errorMsg)){
                                        echo "<label style=' color:#ff0000; '>" .$AdminDataset->_errorMsg . "</label>";
                                    }
                                    ?>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

