<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <!--link to style sheet-->
    <link href="/css/style.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <title>Onboard</title> <!--tittle-->
</head>

<body role="document">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="navbar-brand brand">
                <li style="display: block; margin-right: auto; margin-left: 0;">
                    <img src="../../images/logo_krm.png"> <!--logo of the header-->
                </li>
            </ul>
        </div>
        <div>
            <ul>
                <div class="nav-item d-sm-inline-flex">
                    <!-- link to add candidate -->
                    <a href="../../registration.php"> <button class="btn btn-light btn-lg btn-outline-secondary" style="font-size: 25px; margin-right: 5px;">Add Candidate</button></a>
                    <!-- check if there is an id in session -->
                    <?php if(isset($_SESSION["id"])) : ?>
                    <form method="post" action="index.php?redirect=<?php echo "http://". $_SERVER["HTTP_HOST"] . "/index.php"?>">
                        <!-- button to log out and end session -->
                        <button id="logOut" type="submit" name="logoutButton" class="btn btn-danger btn-lg" value="Log Out";><i class="bi bi-box-arrow-right" style="font-size: 25px; text-emphasis-style: none;"></button></i>
                    </form>
                    <?php endif; ?>
                </div>
            </ul>
        </div>
    </div>
</nav>




